spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hiberDb
    username: root
    password: root
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
